version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sca_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sca_user
      POSTGRES_PASSWORD: sca_pass
      POSTGRES_DB: sca_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.17.0
    container_name: sca_migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://sca_user:sca_pass@db:5432/sca_db?sslmode=disable",
      ]

volumes:
  db_data:
